
WX-session-url: https://api.weixin.qq.com/sns/jscode2session
appid: wx0674242876242421
secret: 6ef2a4ad409320bba883c07266bcaa4f
#secret: ca8527194e9251e466a122d8c383f115


server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviedb?requireSSL=true&useSSL=true&verifyServerCertificate=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: IWannaSee
